### PR TITLE
Fix/emp 21164

### PR DESCRIPTION
**Pull request by udayasri**

### CODE REVIEW

**Comment by rdktrnwskbsg** [comment]
This solutions seems to work for player seek but for **PIP mode it still allows to seek over ads**

**Comment by udayasri** [comment]
> This solutions seems to work for player seek but for **PIP mode it still allows to seek over ads**

I think this behaviour should be handled in the client side. Client app can easily use this api. 
`https://developer.apple.com/documentation/avkit/avplayerviewcontroller/1627633-requireslinearplayback`

`pipController.requiresLinearPlayback = true // while playing the ads`

**Comment by rdktrnwskbsg** [comment]
So just to be clear - we are not able to handle PIP behaviour on any of our iOS SDKs. The PIP SSAI solution should be handled on client side, which means whitelabel iOS app. Is it right?

**Comment by shobaki** [comment]
> So just to be clear - we are not able to handle PIP behaviour on any of our iOS SDKs. The PIP SSAI solution should be handled on client side, which means whitelabel iOS app. Is it right?

Yes you are right, that would be [white-label-native-mobile project](https://github.com/EricssonBroadcastServices/white-label-native-mobile). However, that app (and the [white-label-native-tv](https://github.com/EricssonBroadcastServices/white-label-native-tv)) uses the [rn-player](https://github.com/EricssonBroadcastServices/rn-player) module where I believe this type of initialisation code could be placed. 

Fyi @simonwallin

**Review by rdktrnwskbsg — APPROVED** [review]

**Pull request merged**
